

all: clean build image

clean:
	rm -rf build

build:
	env GOOS=linux GOARCH=arm64 go build -o build/linux/arm64/
	env GOOS=linux GOARCH=amd64 go build -o build/linux/amd64/
	env GOOS=darwin GOARCH=arm64 go build -o build/darwin/arm64/
	env GOOS=darwin GOARCH=amd64 go build -o build/darwin/amd64/

image:
	docker buildx build --platform linux/arm64/v8,linux/amd64 . -t ${WARP_REPO}/${WARP_ENV}-keys-updater:${WARP_VERSION} --no-cache --push

# WARP_VERSION=$(warpctl ls version -b -d) make
